### ISSUE TITLE
Proposal: [ANDROID] move inAppBrowser intents from onPageStarted to shouldOverrideUrlLoading

### ISSUE THREAD

**Issue by jcesarmobile** [cordova/cordova-discuss#10]
I created a mail about this on the developer mail list on April 3rd but only @agrieve answered, and as this is the new way of discussing things I bring it here again:

**Comment by jcesarmobile** [comment]
Original message:

I've been looking into issues and I have seen this one:
https://issues.apache.org/jira/browse/CB-8180

Right now the code to handle the tel links is inside the onPageStarted

if (url.startsWith(WebView.SCHEME_TEL)) {
                try {
                    Intent intent = new Intent(Intent.ACTION_DIAL);
                    intent.setData(Uri.parse(url));
                    cordova.getActivity().startActivity(intent);
                } catch (android.content.ActivityNotFoundException e) {
                    LOG.e(LOG_TAG, "Error dialing " + url + ": " + e.toString());
                }
            }

But the problem is, it launchs the intent and try to open the web page, so when you come back from the intent you see a "couldn't load the url" page on the app.

I've tried to use the view.stopLoading() but it doesn't seem to stop it.
The issue only talks about the tel links, but I suppose that will happen with sms, mailto and some other links.

So, I think a solution might be to move that code to shouldOverrideUrlLoading function.

Is there any reason of doing this on the onPageStarted instead of using the shouldOverrideUrlLoading?

**Comment by jcesarmobile** [comment]
@agrieve answer:
shouldOverrideUrlLoading is what the main cordova webview uses,  so that's
certainly the right approach. I believe it should also add
CATEGORY_BROWSABLE to the intent to ensure that the user is prompted to
confirm whether they actually want to make the call.

**Comment by jcesarmobile** [comment]
The issue has been now assigned to @infil00p and on his comment on the issue he said:
 This will probably be discussed on the list.

But I don't remember seeing this discussed on the mail list appart from my mail.

**Comment by infil00p** [comment]
I asked what this should do in the ideal case.  It should be in
InAppBrowser's shouldOverrideUrlLoading.  Like most of our plugins, I kinda
want to re-write it all, but doing that just shows that I don't know what's
going on with this plugin.  I think there's two issues that are directly
related to what you just talked about on this.

**Comment by jcesarmobile** [comment]
The issue was resolved long time ago, closing...
