### ISSUE TITLE
Proposal: Adding custom label for contacts manager

### ISSUE THREAD

**Issue by typevitor** [cordova/cordova-discuss#13]
I'm developing an app that needs to add custom labels on contacts using the contacts plugin. I saw that the custom label is not implemented. How possible is to implement this? 

I make some ajusts in the plugin in my project, but only in the Android app.

**Comment by purplecabbage** [comment]
Adding a link to the original PR.
https://github.com/apache/cordova-plugin-contacts/pull/67

@shazron Can iOS Contacts have custom phone number label fields. like [ 'work', 'home', 'emergency only'] ? In the last case, emergency only was a custom label that someone had defined.

@nikhilkh  Windows only appears to support the types listed in ContactPhoneKind (https://msdn.microsoft.com/en-us/library/windows/apps/windows.applicationmodel.contacts.contactphonekind) Are custom types allowed somehow? Windows also includes a description field, which may add similar value.

**Comment by shazron** [comment]
I think so: ABMultiValueAddValueAndLabel (deprecated in iOS 9.0). We're suppose to use Contacts.framework now... (new in iOS 9)

**Comment by shazron** [comment]
[CNLabeledValue](https://developer.apple.com/library/prerelease/ios/documentation/Contacts/Reference/CNLabeledValue_Class/index.html)

**Comment by purplecabbage** [comment]
If someone implements this and sends us an updated pull request we will review and consider it.
