### ISSUE TITLE
Proposal: Unified logging

### ISSUE THREAD

**Issue by daserge** [cordova/cordova-discuss#14]
# Cordova unified logging

__Note__: The issue is associated with [Cordova-lib refactoring proposal ](https://github.com/cordova/cordova-discuss/pull/12).

#### 1. `cordova-lib` and cordova `platforms` have logging set up inconsistently

__Current implementation details__:
- `cordova-lib` uses `EventEmitter`, which is further listened in `cordova-cli` and redirected to `console` calls,
- Cordova `platforms` use `console` methods directly.

This leads to the following issue: __log level of `cordova-cli` doesn't affect `platforms` at all__.

__Proposed solutions__:  
__Variant A__: Platforms can use `EventEmitter` passed as a dependency module via `PlatformApi`' interface (f.e. as a ctor parameter).  
In case of CLI-mode `cordova-lib` `EventEmitter` will be used (and logs handling will be unified therefore).  
In case of platform-standalone mode `EventEmitter` will be defaulted in the platform.  
__Variant B__: Pass `logger` class from `cordova-lib` down to `platforms` and call its methods further.

__Variant A__ is recommended as it separates aspects of events emitting from logging and is more flexible in terms of substituting logger module.

---
#### 2. The log messages aren't standardized

__Proposed solution__:
- `logger` module verbosity-based prefixing can be used (`WARN :`, `ERROR:`, etc.),
- Emit objects rather than just messages in case of errors (f.e. use `CordovaError` extended with an error code).

---
#### 3. Platforms logging mechanism does not allow plugging in a custom handling code/module (integration & custom transport levels)
__Proposed solution__: 
- Top-level `cordova.on` event can be used to subscribe for error events since `cordova-lib`' `EventEmitter` will be used,
- Additionally `logger` module used in CLI or platform-standalone mode can be substituted to a pluggable one, for example [winston](https://github.com/winstonjs/winston),
- Some multi-transport logger module can be used to use transports other than `console` (file, couchdb, etc.).

---
#### 4. Errors from third-party components (`ant`, `gradle`, etc.) can't be easily distinguished
__Proposed solution__: 
Attach to `process.spawn` `stdout` and `stderr`, supply caught errors with their source in `meta` object (f.e. extended `CordovaError` - see `2.`).

**Comment by stevengill** [comment]
Great writeup! I've been wanting to look at our logging support and standardizing it across our projects. 

I like variant A and the idea that can try out different loggers.

I also like the idea of having error codes we define/standardize and use for cordova that persist among our various projects.

**Comment by muratsu** [comment]
:+1: 
I'm all in for a standardized logging. Error verbosity will also give us the ability to debug things much more efficiently. This will make verbose mode much more useful.

**Comment by nikhilkh** [comment]
This is great! I like variant A.

**Comment by purplecabbage** [comment]
+1 Variant A

**Comment by nikhilkh** [comment]
Looks like most of this is implemented now. We should close this issue.
