### ISSUE TITLE
Proposal: Plugin docs generation

### ISSUE THREAD

**Issue by daserge** [cordova/cordova-discuss#15]
# Cordova docs-gen proposal

Initial points for investigation were the following:
* Code to Docs tool selection -> proposing [JSDoc](http://usejsdoc.org/) for following reasons:
    * `JSDoc` parses code-tree, which means smart code analysis, internal linking and less comments verbosity in code,
    * `JSDoc` is extensible via JS plugins,
    * `JSDoc` presentation is customizable via templates,
    * Existing code uses `JSDoc` format mostly;
* Generated docs renderer selecting -> Use either `JSDoc` (HTML output) or [jsdoc-to-markdown](https://www.npmjs.com/package/jsdoc-to-markdown) (md output),
    * `JSDoc` generated separate HTML pages, which further needs to be combined and converted to Markdown,
    * In case of `jsdoc-to-markdown` we get Markdown output, although there are following issues:
        * [`jsdoc-to-markdown` currently does not support `jsdoc` configuration](https://github.com/jsdoc2md/jsdoc-to-markdown/issues/45) so that JSDoc plugins can't be used as is,
        * We will need to [set up code linking](http://usejsdoc.org/about-configuring-default-template.html) (it is included by `JSDoc` by default but not by `jsdoc-to-markdown`);
* Create `JSDoc` plugin for handling Cordova-specific tags like `supported-platforms`, `quirks` (or `windows-quirks`, `android-quirks`, ...), etc.,
    * Investigate possibility: Link to quirks/examples (similar to [tutorial tag](http://usejsdoc.org/tags-tutorial.html)) instead of inlining to reduce noise in the code (this will also help as existing docs will be moved as is),
        * [@partial plugin](https://github.com/jsdoc3/jsdoc/blob/master/plugins/partial.js) can be used for this purpose. Using it along with markdown plugin allows just to move big docs chunks from plugin docs to function/class-related files (there is also a @tutorial plugin, but it just inserts a link to separate file),
        * JSDoc @typedef tag can be used for linking to separate file - this has a drawback that separate file has to be in JSDoc comments format (while we have md);
* Use custom `JSDoc` template to integrate with `cordova-docs` site,
    * The documentation will need to be rebuilt on each code change. Investigate a proper way to do this? (CI tools, precommit hook, prepackage hook for npm).

__Prototypes__:
* [Prototype based on camera plugin](https://github.com/MSOpenTech/cordova-plugin-camera/blob/docs-gen/README-gen.md) - docs are generated by [`jsdoc-to-markdown` command](https://github.com/MSOpenTech/cordova-plugin-camera/blob/docs-gen/package.json#L45),
    * Pros
        * Markdown format,
        * One file,
    * Cons
        * External content pasting (big chunks of documentation like Quirks, examples, extra description, etc.) is not currently supported,
        * No links to code;
* [JSDoc generated docs](https://htmlpreview.github.io/?https://raw.githubusercontent.com/MSOpenTech/cordova-plugin-camera/docs-gen/docs/navigator.module_camera.html) using [@partial](https://github.com/MSOpenTech/cordova-plugin-camera/blob/2defa1370d143c21868b19b74f29ebb9fefa4d04/www/Camera.js#L94) and [markdown plugin](https://github.com/MSOpenTech/cordova-plugin-camera/blob/2defa1370d143c21868b19b74f29ebb9fefa4d04/jsdoc2md/conf.json#L10) with [JSDoc command](https://github.com/MSOpenTech/cordova-plugin-camera/blob/docs-gen/package.json#L46),
    * Pros
        * Supports pasting of external docs via @partial + markdown plugins,
        * Supports linking to code with pretty-print and line numbers,
    * Cons
        * Multiple HTML files as an output,
        * Needs to be converted to Markdown by some other tool.

Thoughts? 
Perhaps there are some better tools or methods I have missed?

**Comment by daserge** [comment]
__Upd__: After setting up underlying JSDoc and turning on partial and markdown plugins [@partial worked](https://github.com/MSOpenTech/cordova-plugin-camera/blob/06854817ac41240ed8cf6d6e6634ec424302a4c4/README-gen.md).
Although there are issues with combining of @partial and other JSDoc tags like @param: [see text after Tizen Quirks](https://github.com/MSOpenTech/cordova-plugin-camera/blob/06854817ac41240ed8cf6d6e6634ec424302a4c4/README-gen.md#tizen-quirks).

**Comment by daserge** [comment]
Used markdown-links in JSDoc comments to the moved big docs chunks (quirks, extra examples, etc.) to the Handlebars template file:
[Result](https://github.com/MSOpenTech/cordova-plugin-camera/blob/49ccbb05794a5ce300f9a2572d6b94f3ad0dd612/README-gen.md)

How it works:
* [Specifying a link in template](https://github.com/MSOpenTech/cordova-plugin-camera/blob/49ccbb05794a5ce300f9a2572d6b94f3ad0dd612/jsdoc2md/README.hbs#L96)
* [Linking to a big doc chunk in the source code](https://github.com/MSOpenTech/cordova-plugin-camera/blob/49ccbb05794a5ce300f9a2572d6b94f3ad0dd612/www/Camera.js#L89)
* [Result in the generated docs](https://github.com/MSOpenTech/cordova-plugin-camera/blob/49ccbb05794a5ce300f9a2572d6b94f3ad0dd612/README-gen.md#cameragetpicturesuccesscallback-errorcallback-options) -> [Supported platforms](https://github.com/MSOpenTech/cordova-plugin-camera/blob/49ccbb05794a5ce300f9a2572d6b94f3ad0dd612/README-gen.md#camera-getPicture-supported-platforms)

**Comment by daserge** [comment]
__Upd__: [Renamed __hbs__ template to __md__](https://github.com/MSOpenTech/cordova-plugin-camera/blob/b7d2af501c2e633d98fc0e2551e5caf50730f902/jsdoc2md/README.md) to be viewable on Github.

**Comment by nikhilkh** [comment]
@axemclion @dblotsky Can you please review and comment.

**Comment by daserge** [comment]
[Latest generated docs version](https://github.com/MSOpenTech/cordova-plugin-camera/blob/docs-gen/README-gen.md)

**Comment by nikhilkh** [comment]
@daserge We've already converted this to a proposal. Closing this now.
