### ISSUE TITLE
Question: Format for discussion new ideas

### ISSUE THREAD

**Issue by axemclion** [cordova/cordova-discuss#2]
As I understand from the README, this is a repo to discuss new ideas for Cordova. I think it would help if we lay down guidelines on how to create new files for new ideas. Is the idea here that we use github instead of google docs ? 

Would help if that is elaborated in the README, and we have suggestions on how to create a new idea.

**Comment by stevengill** [comment]
When I created this repo, I was hoping to replace the google doc workflow we use with this instead. It is easier to keep track of proposals here than on github. Also opens up discussions to the outside community.

I was thinking we use the issue tracker as a first place to propose ideas or big changes. Then it could be moved into a proposals folder? 

Open to suggestions. 

Agreed it should be formalized a bit.

**Comment by axemclion** [comment]
I think we do need each proposal as a file so that folks who are not interested in the history, but just want to look at the state of the proposal read the file in the proposals folder. If anyone is interested in the history and discussions, they could look at all the pull requests, and the discussions on the pull requests ?

**Comment by axemclion** [comment]
Also, should we send a mail to the mailing list, indicating the existence of this repo ? I am not sure if everyone read the cookie proposal, and realized that this repo exists.

**Comment by stevengill** [comment]
Sure. I was waiting until I had a proposal to show haha. Good investigative work Parashuram. 

Proposals in a proposals folder + PRs sound good to me. We can still use issues for early discussions or trying to get outside developers to contribute

**Comment by nikhilkh** [comment]
+1 @stevengill on replacing google-docs with this. It's public, searchable, and allows more people to participate. I really like what C# team is doing here:https://github.com/dotnet/roslyn/issues/347. An issue for a proposal with meaningful [labels](https://github.com/dotnet/roslyn/labels). Issues help for easy comment stream and collaboration in github.com. Once they are implemented - the issues should be marked Closed and moved to appropriate docs in the cordova-docs repo.

**Comment by axemclion** [comment]
Closing issue as we now have a document that talks about the process.
