### ISSUE TITLE
Is Amazon Fire-OS still supported?

### ISSUE THREAD

**Issue by brodybits** [cordova/cordova-discuss#32]
Unanswered questions:
- https://groups.google.com/forum/#!topic/phonegap/6oZfxBc4hPc
- litehelpers/Cordova-sqlite-enterprise-free/issues/2

/cc @scottjpearson

**Comment by stevengill** [comment]
Amazon committers have been gone from the project for a while. Last we heard they said to target android to deploy to fireos 5.0+ devices. We are in the process of removing support of fireos from cordova [1].

[1] https://issues.apache.org/jira/browse/CB-10121

LMK if you have more questions!

**Comment by brodybits** [comment]
Thanks!
