### ISSUE TITLE
[Windows] Universal Windows 8.1 version?

### ISSUE THREAD

**Issue by brodybits** [cordova/cordova-discuss#40]
I noticed when I installed a new version of Visual Studio 2015 (Community Edition) for testing that it is possible to generate a "Universal Windows 8.1" Javascript project that can run on both Windows 8.1 and Windows Phone 8.1. While this will eventually be superseded with Windows 10, do we want to consider supporting this one for now?

Unknown: I don't know if it is possible to get a native C++ library working for "Universal Windows 8.1".

**Comment by nikhilkh** [comment]
Cordova-windows uses a "Universal Windows 8.1" JS project and supports deployment on phone and desktop. This is currently the default for cordova-windows platform as the windows-target-version default value is 8.1.
When setting the value of windows-target-version to 10.0, UWP project is used which only works for Windows 10.
Yes, a native C++ library is supported for "Universal Windows 8.1".
