### ISSUE TITLE
Kill off our wiki

### ISSUE THREAD

**Issue by purplecabbage** [cordova/cordova-discuss#46]
Our wiki [1] has quietly been overgrown with weeds and has returned to the wild.
I think it is time to move any content that isn't already in a guide over to our docs, and set the wiki site free.

[1] https://wiki.apache.org/cordova/FrontPage

**Comment by nikhilkh** [comment]
+1 - are you proposing we delete the content or add a big deprecated banner? What content needs to be moved?

**Comment by purplecabbage** [comment]
yes, one by one, we delete pages from the wiki, move them to docs or coho where appropriate, and then leave a message pointing to the new home.
Eventually the wiki will be empty and we can bury it.

**Comment by purplecabbage** [comment]
Done, the frontpage is still there and has links to other locations for info, for the time being.

**Comment by filmaj** [comment]
Thanks for taking the time to do it!
