### ISSUE TITLE
cordova prepare needed for sqlite plugin on iOS with Xcode 8

### ISSUE THREAD

**Issue by brodybits** [cordova/cordova-discuss#55]
For some reason I need to do `cordova prepare` before running an app with Cordova-sqlite-storage on iOS with Xcode 8. If I do `cordova prepare` then Cordova-sqlite-storage works for me on my iOS 8.1.2 device (iPhone 4S) and iOS 10.0.2 device (iPhone 5S), with or without the WKWebView plugin. I did the testing with the built-in test suite and https://github.com/brodybits/Cordova-sqlite-bootstrap-test. I think this explains the problems reported in litehelpers/Cordova-sqlite-storage#567 and litehelpers/Cordova-sqlcipher-adapter#22.

Unfortunately I did not have a chance to test if this is a problem with any other plugins or not. I would be happy to do some further testing to help narrow the problem when I get a chance in the next couple weeks or so. For now I will simply document the use of `cordova prepare` as a requirement for iOS and as a recommendation for the other platforms.

**Comment by MehdiGuelloub** [comment]
Hello,
I don't understand, when do I need to use `cordova prepare`? after `ionic platform add ios`? and is it `cordova prepare ios` or just `cordova prepare`?

PS: I'm new in hybrid developing

**Comment by brux88** [comment]
I upgraded to ios 10 and does not work sqlite, a solution has been found?

**Comment by brodybits** [comment]
> I don't understand, when do I need to use cordova prepare? after ionic platform add ios?

I think so (I did not try iOS 10 with Ionic)

> and is it cordova prepare ios or just cordova prepare?

Either one

**Comment by brodybits** [comment]
Now reported in https://issues.apache.org/jira/browse/CB-12046

**Comment by brodybits** [comment]
Issue goes away in cordova-cli 6.4.0, closing.
