### ISSUE TITLE
Support generic platforms

### ISSUE THREAD

**Issue by purplecabbage** [cordova/cordova-discuss#64]
Currently, unless your new platform has a known name, you cannot use it with the cordova-cli.

cordova-lib has numerous checks for whether or not the platform is in the list of know platforms.  This is why you can `cordova platform add cordova-android` and then run `cordova run android`, the alias mapping prevents new platforms from working.

This was recently discussed on the mailing list, some important excerpts here:
[@shazron]

> re: https://issues.apache.org/jira/browse/CB-11346?focusedCommentId=15875577&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15875577
> 
> Looks like there is more to it than the patch. The error occurs here: https://github.com/apache/cordova-lib/blob/a9605411ab007d700849c971043f0c211c06100c/cordova-lib/src/cordova/platform.js#L389
> 
> All three conditions have to be satisfied:
> 
> version (from package.json)
> platform name (from package.json name, has to be in the form of cordova-XXXX where XXX is the actual platform name)
> platform name exists in platformConfig.json file
> We would have to remove checks 2 and 3, but not sure of the impact since platformConfig.json contains information that is probably needed elsewhere (ideally it would exist in the platform itself!)
> 

[@shazron]

> The src/platforms/platforms.js file touches almost all commands, particularly the use of the getPlatformAPI call, so removing this is tricky -- but at least there is only one API call to abstract away.

Ideally platform name/alias should be part of the platformAPI or just part of it's package.json
cli commands that touch platforms could potentially just take the specified platform string and look inside `platforms/` for a folder with that name.  The location of the platformAPI is standard within that forlder.

**Comment by stevengill** [comment]
Lets do it.

We also got https://issues.apache.org/jira/browse/CB-10239 which is kind of related.

We don't necessarily need to remove/move the aliasing. A quick fix would be just to allow non known platforms to run. Essentially skip the aliasing if it isn't in the known platforms list.

**Comment by shazron** [comment]
+1
In `getPlatformAPI` the only use of `platformConfig.json` is https://github.com/apache/cordova-lib/blob/master/cordova-lib/src/platforms/platforms.js#L49 and the error handler that calls [`apiCompatibleSince`](https://github.com/apache/cordova-lib/blob/master/cordova-lib/src/platforms/platforms.js#L60) -- those are easily changed/removed. 

The`platformConfig.json` file is a legacy file that is only used for `PlatformAPIPoly.js`, which is used when a platform does not conform to the Platform API. It could be time to remove this file and its usage?

**Comment by stevengill** [comment]
Browser and other older platforms don't have API.js yet. So they rely on `PlatformAPIPoly.js`.

**Comment by purplecabbage** [comment]
Who wants to do it? I think we have enough info/support to get rolling

**Comment by stevengill** [comment]
I'll dive in

**Comment by purplecabbage** [comment]
Me!

**Comment by purplecabbage** [comment]
did it, coming in 7
