### ISSUE TITLE
Cookie work!

### ISSUE THREAD

**Issue by iRomano** [cordova/cordova-discuss#65]
I'm little confused, because in my cordova app (iOS, Android) COOKIES is work!
I'm use last cordova.
And i have a question: it's a bug or really cordova enable cookies?

**Comment by purplecabbage** [comment]
cookies do work, but I would not consider them reliable.  Cookies are typically more server based than anything else, and not completely inline with the way cordova apps work.
Use localStorage to keep persistent data around.
