### ISSUE TITLE
Proposal: Cordova Plugin Search

### ISSUE THREAD

**Issue by muratsu** [cordova/cordova-discuss#7]
### Cordova Plugin Search

Move to NPM poses new challenges around branding and plugin discoverability. Below I'll go into details of this problem and how it's tackled by other open source communities. You can also find a proposal for Cordova at the end.

#### NPM

![](http://i.imgur.com/ISiw4eF.png)

Currently NPM doesn't support customized search queries. It's designed to be "one size fits all". This is not ideal as we want cordova users to be able to quickly identify plugins and download them as friction-less as possible. In this case, a naive cordova developer might search for the query "cordova" instead of "ecosystem:cordova". 

#### npm cli

![](http://i.imgur.com/bLiumyl.png) 

NPM cli search is not a good solution either. Search in this case will download a local copy of all npm meta data from npm couchdb and will perform search afterwards. As can be seen from [this](https://github.com/npm/npm/issues/6016) GH issue, it's really hard. 
> (1) command took 20 minutes; (2) about 1000 lines of output; (3) peak swap usage 1.81GB; (4) network bandwidth reasonably small; (5) high CPU usage for the full 20 minutes; (6) high disk I/O averaged 3 to 10 MB/sec continuously probably thrashing; (7) the swapfile expanded to permit "npm search" to complete now takes up 1/7 of the whole drive.

#### gulp

![](http://i.imgur.com/kjjIq6T.png)

Gulp relies on some 3rd party service to deliver it's search results. (http://npmsearch.com/ in this case). Npmsearch relies on [elasticsearch](https://www.elastic.co/) to provide super fast search results. Filtering is achieved by using keywords (`gulpplugin`). There's also a [blacklist](http://gulpjs.com/plugins/blackList.json). Technically gulp plugin search is a static search page. It works like the following:

- user visits plugin page
- page makes a cross-domain query on npmsearch
- user downloads a list of all available plugins (up to 804ms - 557kb - 1533 entries)
- filters blacklisted plugins
- search page is presented (under 1.25s total)

Once the page is presented, search bar is used to further filter plugins.

####  gruntjs

![](http://i.imgur.com/WJrB4L3.png)

Grunt stores the plugin data on their own [servers](http://gruntjs.com/plugin-list.json). They're currently collecting plugin information by some server side script. But similar to gulp, client downloads are presented as one big json data and all the searches are done on client side after it's downloaded. Search data seems more optimized compared to gulp (221kb - 719ms - 4403 entries)

#### bowerjs

![](http://i.imgur.com/YH4TS7U.png)

Bower also stores the plugin data on their own [servers](https://bower-component-list.herokuapp.com/). (1.9mb -2.30s - 28k entries) The rest is identical to bower and grunt.

#### cordova

![](http://i.imgur.com/I06mPCQ.png)

After my research, I've concluded that serving pluginsearch results as json is the way to go. I've bare-bones of a search page implementation available on [GH](https://github.com/muratsu/cordova-plugin-search) (see screenshot above). It follows the same design principles with gulp/grunt/bower. I would like to get feedback from Cordova devs on the following topics:

1.  Should we host/implement a service to collect Cordova related plugin information or rely on a 3rd party service such as "npmsearch" ?
2.  Do we want to maintain a list of blacklisted plugins like bower? If so, what are the rules for adding a plugin to blacklist? Where and how are we going to maintain this file?
3.  What are the most important things to display on search page? Currently I'm thinking `version`, `plugin name`, `plugin description` and `stars/rating`. What else is important? 

I'm hoping to get our new search page prototype on it's feet as soon as possible to get feedback from extended community! Please feel free to share your ideas and provide feedback.

**Comment by TimBarham** [comment]
I find `number of downloads` useful, as it helps determine which plugins have traction (so say I'm looking for a Facebook plugin, and there are 50 of them, which ones are people actually using).

**Comment by axemclion** [comment]
What about supported platforms ?

**Comment by muratsu** [comment]
@axemclion, that's a really good point. I believe we currently rely on tags for supported platforms. I can parse and display supported platforms

**Comment by gorkem** [comment]
I think we need the filter (blacklist) in order to filter tools and platforms. I think blacklist should only be used for filtering out duplicates, deprecated plugins and entries that are not really plugins.

**Comment by stevengill** [comment]
Good idea on having a blacklist for platforms/tools. 

Demo is at http://people.apache.org/~muratsu/

Since modules on npm can't have caps, it would be nice if the search auto lowercased. Currently, searching for "Cordova" will return nothing but "cordova" works fine.

**Comment by muratsu** [comment]
# npm search page milestones
Below I've created some tasks (and jiras) for the work that needs to be done in this area. 

**v0: Hackathon to Cordova**:
- [x] create a MVP
- [x] test it on latest ie & chrome
- [x] ensure community consensus
- [ ] push it to apache (Pending PR)

**v1: Integration**:
- [ ] Create a link from old plugin search page
- [ ] Create a faq about how page works
- [ ] Add last updated date to plugin cards
- [ ] Add download count to plugin cards
	- https://github.com/npm/download-counts
- [ ] Add analytics (google?)
- [ ] Extended browser testing
	- [ ] Test css on ie, ff, safari, chrome
	- [ ] Test different form factors

**Known Issues**
- [ ] Two XHR calls for getting plugins may not be necessary. Increase the number of first XHR call to 200 [CB-9152](https://issues.apache.org/jira/browse/CB-9152)
- [ ] Platform tag boxes look bad in iphone  [CB-9153](https://issues.apache.org/jira/browse/CB-9153)
- [ ] Lowercase search queries [CB-9154](https://issues.apache.org/jira/browse/CB-9154)

**Comment by nikhilkh** [comment]
This has been shipped now at https://cordova.apache.org/plugins/
