### ISSUE TITLE
Proposal: cordova-serve

### ISSUE THREAD

**Issue by TimBarham** [cordova/cordova-discuss#8]
I started a thread about this on the dev list, but figured it would be good to have it here.

A while back we duplicated a bunch of `cordova serve` code in `cordova-browser` so that `cordova run browser` would launch from a server rather than the local file system. At the time, the desire was expressed that ultimately we should avoid the duplicated code and have a separate `cordova-serve` module. Since this module would also be useful for the plugin simulation stuff I've been working on, I've been taking a look at it recently.

I have an initial prototype implementation (which also includes some functionality I need for the plugin simulation work) [here](https://github.com/TimBarham/cordova-serve), changes to `cordova-browser` to use it [here](https://github.com/MSOpenTech/cordova-browser/compare/42bd8f1985041ba26b33408372b218218f7c6183...tb-cordova-serve), and corresponding changes to cordova-lib [here](https://github.com/MSOpenTech/cordova-lib/compare/bddcc8f2d709a55df2d91c14def61212843a14e8...tb-cordova-serve).

Primary question is where this module would live. Likely possibilities are:

1. As a new Cordova repository.
2. Within the `cordova-lib` repository (it would be its own npm module - its source would live in a `cordova-serve` folder next to the `cordova-lib` folder).

The advantage of the second approach is that it avoids proliferation of Cordova repositories, particularly for a small helper module that is required by `cordova-lib`, and it starts implementing the whole reason `cordova-lib` is in a folder within the `cordova-lib` repo (so we can have multiple packages in the repo). However, it has some disadvantages:

* It will have to share `appveyor` and `travis` configuration files with `cordova-lib`.
* It will not be installable via npm from git (since npm requires package.json at the root of the repo).

I'm interested in opinions on what would be the best approach.

**Comment by TimBarham** [comment]
My preference (if it weren't for the negatives) would be that it live within the `cordova-lib` repo - it seems overkill to have a new repo for a small helper module that is required by `cordova-lib`. And I think not being able to `npm install` from github is a minor annoyance at most. However, I wonder if having to share appveyor and travis configuration makes this approach untenable.

**Comment by purplecabbage** [comment]
+1 to keeping it in a cordova-lib dir.
npm install from github isn't that important imho, people can still install it from a local cloned repo.

for the testing, I would just expect to see some isolated tests defined in the cordova-lib/cordova-serve/package.json.  Ultimately there should not be a lot of change in this module so it should be well tested directly before being committed/npmPublished so having one extra test step in our CIs should be fine.

My only question is, if this is functionality used by cordova-lib, does cordova-lib use it directly as if it were part of the cordova-lib module ( since it is in the same repo ), or does cordova-lib define a dependency on a particular npm published version of cordova-serve?

**Comment by TimBarham** [comment]
Regarding the last question - I was thinking the latter. It's in a same repo, but not in the `cordova-lib` npm package.

**Comment by TimBarham** [comment]
So... Since adding `cordova-serve` to the `cordova-lib` repo, I've been playing around with the `coho` release tools to get a feel of how it will look getting a release of `cordova-serve` out, and I've hit an  issue...

Because release versions are tied to git labels, `cordova-serve` versions will always be tied to `cordova-lib` versions. This means either we need to keep their releases in sync, or, if not, when we release one, the version of the other will have to be moved forward "unnaturally" even if we're not releasing it (for example, `cordova-lib` might have a major version bump which would be forced onto the next release of `cordova-serve`, even if it only had bug fixes and so should only get a patch version change so other consumers pick up the changes appropriately).

I don't like the idea that there version numbers are dependent on each other when it may well be nice for `cordova-serve` to have an independent release cadence. In fact, this would be one of the *benefits* of having things in separate modules. I'd like to have the freedom to do releases of `cordova-serve` independently of `cordova-lib`, particularly when there are changes purely for the benefit of consumers other than `cordova-lib`.

Anyone have thoughts on this? Something I'm missing that could make this work?

**Comment by TimBarham** [comment]
[one possibility that occurs to me is that we use a different tagging system for "non-primary" modules like `cordova-serve` - 'serve@version' for example - and modify our "most recent tag"  logic to account for that, depending on which module you are currently working with]

**Comment by TimBarham** [comment]
Hey @stevengill - do you have any thoughts on this? I have a PR that implements the prefix for `cordova-serve` - seems to work pretty well. Any downsides you can think of?

**Comment by stevengill** [comment]
By git labels I am assuming you mean git tags. 

The versions of `cordova-lib` and `cordova-serve` should not be tied together. We can easily add a new tagging system for non-primary modules like `cordova-serve`. We would have to modify our release process to not use the last tag but take a supplied tag. I'm more worried about our RELEASENOTES though. We use differences between git tags to generate them. Sharing one git history seems problematic to me. Going to cause more work to get our RELEASENOTES in order. No way to automate this I think. 

I'm thinking more and more that maybe we should just have a 1 npm module to 1 repo rule.

**Comment by TimBarham** [comment]
Thanks Steve. And yeah, I meant tags :smile:.

Regarding versioning... I have a PR [here](https://github.com/apache/cordova-coho/pull/84) that handles versions with prefixes. So versions for the `cordova-lib` package itself would remain as they are. Versions for the `cordova-serve` package would be prefixed with `serve-`. The 'get latest tag' logic is updated to get the latest tag *with the prefix*, if requested. So if you are packaging `cordova-serve`, it looks for the latest tag with the `serve-` prefix. If you are packaging `cordova-lib`, it looks for the latest tag without a prefix. That piece is working.

Regarding RELEASENOTES... That's a good point. Are there currently COHO tools for this? If not, I think it would be easy enough to write them, and the way to determine whether it is `cordova-lib` or `cordova-serve` would be by looking at paths of files in the commit.

1 npm module per repo? Yeah, you may well be right. But I would like to pursue this a little longer to see if we can make it work fairly seamlessly, as it certainly lowers the bar to introducing new modules, which could be nice. If it ends up being more of a pain than it's worth, I'll move `cordova-serve` back out to a separate repo.

**Comment by stevengill** [comment]
Sounds good Tim. I'm all for pursuing it and seeing if we can make it seamless. I'm headed off to nodeconf soon and will be sporadic in my responses until Monday. I'll try to get to the coho PR sometime before Monday.

**Comment by nikhilkh** [comment]
Looks like most of the work for this is done now. @TimBarham Should this issue be closed?

**Comment by TimBarham** [comment]
Yup. It's all done.
